on: push
name: CI
jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.0'
          coverage: none

      - name: Install the dependencies
        run: composer update --no-interaction --no-suggest

      - name: Run PHPStan
        run: composer phpstan

  phpunit:
    name: 'PHP ${{ matrix.php }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.0', '7.1', '7.2', '7.3', '7.4']
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup php
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}

        - name: Composer install
          run: |
              set -e
              composer install --no-interaction --ansi --no-progress --optimize-autoloader
        - name: Execute unit tests
          run: |
              set -e && composer tests
