on: push
name: CI
jobs:
  phpunit:
    name: 'PHP ${{ matrix.php }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0', '8.1', '8.2', '8.3', '8.4']
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup php
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}

        - name: Composer install
          run: |
              set -e
              composer install --no-interaction --ansi --no-progress --optimize-autoloader
        - name: Execute unit tests
          run: |
              set -e && composer tests
